/***************************************************************************//**
* \file cyhal_triggers_psoc4100smax.h
*
* \brief
* PSoC4100Smax family HAL triggers header
*
********************************************************************************
* \copyright
* (c) (2016-2021), Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
*
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#ifndef _CYHAL_TRIGGERS_PSOC4100SMAX_H_
#define _CYHAL_TRIGGERS_PSOC4100SMAX_H_

/**
 * \addtogroup group_hal_impl_triggers_psoc4100smax PSOC4100SMAX
 * \ingroup group_hal_impl_triggers
 * \{
 * Trigger connections for psoc4100smax
 */

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/** \cond INTERNAL */
/** @brief Name of each input trigger. */
typedef enum
{
    _CYHAL_TRIGGER_CPUSS_ZERO = 0, //!< cpuss.zero
    _CYHAL_TRIGGER_CANFD_TR_DBG_DMA_REQ0 = 1, //!< canfd.tr_dbg_dma_req[0]
    _CYHAL_TRIGGER_CANFD_TR_FIFO00 = 2, //!< canfd.tr_fifo0[0]
    _CYHAL_TRIGGER_CANFD_TR_FIFO10 = 3, //!< canfd.tr_fifo1[0]
    _CYHAL_TRIGGER_CANFD_TR_TMP_RTP_OUT0 = 4, //!< canfd.tr_tmp_rtp_out[0]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0 = 5, //!< cpuss.dmac_tr_out[0]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1 = 6, //!< cpuss.dmac_tr_out[1]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2 = 7, //!< cpuss.dmac_tr_out[2]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3 = 8, //!< cpuss.dmac_tr_out[3]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4 = 9, //!< cpuss.dmac_tr_out[4]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5 = 10, //!< cpuss.dmac_tr_out[5]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6 = 11, //!< cpuss.dmac_tr_out[6]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7 = 12, //!< cpuss.dmac_tr_out[7]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8 = 13, //!< cpuss.dmac_tr_out[8]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9 = 14, //!< cpuss.dmac_tr_out[9]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10 = 15, //!< cpuss.dmac_tr_out[10]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11 = 16, //!< cpuss.dmac_tr_out[11]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12 = 17, //!< cpuss.dmac_tr_out[12]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13 = 18, //!< cpuss.dmac_tr_out[13]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14 = 19, //!< cpuss.dmac_tr_out[14]
    _CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15 = 20, //!< cpuss.dmac_tr_out[15]
    _CYHAL_TRIGGER_EXCO_TRIGGER = 21, //!< exco.trigger
    _CYHAL_TRIGGER_LPCOMP_COMP_OUT0 = 22, //!< lpcomp.comp_out[0]
    _CYHAL_TRIGGER_LPCOMP_COMP_OUT1 = 23, //!< lpcomp.comp_out[1]
    _CYHAL_TRIGGER_MSC0_TR_RD_REQ_OUT = 24, //!< msc[0].tr_rd_req_out
    _CYHAL_TRIGGER_MSC1_TR_RD_REQ_OUT = 25, //!< msc[1].tr_rd_req_out
    _CYHAL_TRIGGER_MSC0_TR_WR_REQ_OUT = 26, //!< msc[0].tr_wr_req_out
    _CYHAL_TRIGGER_MSC1_TR_WR_REQ_OUT = 27, //!< msc[1].tr_wr_req_out
    _CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0 = 28, //!< pass[0].dsi_ctb_cmp0
    _CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1 = 29, //!< pass[0].dsi_ctb_cmp1
    _CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE = 30, //!< pass[0].dsi_sar_sample_done
    _CYHAL_TRIGGER_PASS0_TR_SAR_OUT = 31, //!< pass[0].tr_sar_out
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED = 32, //!< scb[0].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED = 33, //!< scb[1].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED = 34, //!< scb[2].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED = 35, //!< scb[3].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED = 36, //!< scb[4].tr_i2c_scl_filtered
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ = 37, //!< scb[0].tr_rx_req
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ = 38, //!< scb[1].tr_rx_req
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ = 39, //!< scb[2].tr_rx_req
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ = 40, //!< scb[3].tr_rx_req
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ = 41, //!< scb[4].tr_rx_req
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ = 42, //!< scb[0].tr_tx_req
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ = 43, //!< scb[1].tr_tx_req
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ = 44, //!< scb[2].tr_tx_req
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ = 45, //!< scb[3].tr_tx_req
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ = 46, //!< scb[4].tr_tx_req
    _CYHAL_TRIGGER_TCPWM_LINE0 = 47, //!< tcpwm.line[0]
    _CYHAL_TRIGGER_TCPWM_LINE1 = 48, //!< tcpwm.line[1]
    _CYHAL_TRIGGER_TCPWM_LINE2 = 49, //!< tcpwm.line[2]
    _CYHAL_TRIGGER_TCPWM_LINE3 = 50, //!< tcpwm.line[3]
    _CYHAL_TRIGGER_TCPWM_LINE4 = 51, //!< tcpwm.line[4]
    _CYHAL_TRIGGER_TCPWM_LINE5 = 52, //!< tcpwm.line[5]
    _CYHAL_TRIGGER_TCPWM_LINE6 = 53, //!< tcpwm.line[6]
    _CYHAL_TRIGGER_TCPWM_LINE7 = 54, //!< tcpwm.line[7]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0 = 55, //!< tcpwm.tr_compare_match[0]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1 = 56, //!< tcpwm.tr_compare_match[1]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2 = 57, //!< tcpwm.tr_compare_match[2]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3 = 58, //!< tcpwm.tr_compare_match[3]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4 = 59, //!< tcpwm.tr_compare_match[4]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5 = 60, //!< tcpwm.tr_compare_match[5]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6 = 61, //!< tcpwm.tr_compare_match[6]
    _CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7 = 62, //!< tcpwm.tr_compare_match[7]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0 = 63, //!< tcpwm.tr_overflow[0]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1 = 64, //!< tcpwm.tr_overflow[1]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2 = 65, //!< tcpwm.tr_overflow[2]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3 = 66, //!< tcpwm.tr_overflow[3]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4 = 67, //!< tcpwm.tr_overflow[4]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5 = 68, //!< tcpwm.tr_overflow[5]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6 = 69, //!< tcpwm.tr_overflow[6]
    _CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7 = 70, //!< tcpwm.tr_overflow[7]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0 = 71, //!< tcpwm.tr_underflow[0]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1 = 72, //!< tcpwm.tr_underflow[1]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2 = 73, //!< tcpwm.tr_underflow[2]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3 = 74, //!< tcpwm.tr_underflow[3]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4 = 75, //!< tcpwm.tr_underflow[4]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5 = 76, //!< tcpwm.tr_underflow[5]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6 = 77, //!< tcpwm.tr_underflow[6]
    _CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7 = 78, //!< tcpwm.tr_underflow[7]
} _cyhal_trigger_source_psoc4100smax_t;

/** Typedef for internal device family specific trigger source to generic trigger source */
typedef _cyhal_trigger_source_psoc4100smax_t cyhal_internal_source_t;

/** @brief Get a public source signal type (cyhal_trigger_source_psoc4100smax_t) given an internal source signal and signal type */
#define _CYHAL_TRIGGER_CREATE_SOURCE(src, type)    ((src) << 1 | (type))
/** @brief Get an internal source signal (_cyhal_trigger_source_psoc4100smax_t) given a public source signal. */
#define _CYHAL_TRIGGER_GET_SOURCE_SIGNAL(src)      ((cyhal_internal_source_t)((src) >> 1))
/** @brief Get the signal type (cyhal_signal_type_t) given a public source signal. */
#define _CYHAL_TRIGGER_GET_SOURCE_TYPE(src)        ((cyhal_signal_type_t)((src) & 1))
/** \endcond */

/** @brief Name of each input trigger. */
typedef enum
{
    CYHAL_TRIGGER_CPUSS_ZERO_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_ZERO, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.zero
    CYHAL_TRIGGER_CPUSS_ZERO_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_ZERO, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.zero
    CYHAL_TRIGGER_CANFD_TR_DBG_DMA_REQ0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CANFD_TR_DBG_DMA_REQ0, CYHAL_SIGNAL_TYPE_LEVEL), //!< canfd.tr_dbg_dma_req[0]
    CYHAL_TRIGGER_CANFD_TR_FIFO00 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CANFD_TR_FIFO00, CYHAL_SIGNAL_TYPE_LEVEL), //!< canfd.tr_fifo0[0]
    CYHAL_TRIGGER_CANFD_TR_FIFO10 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CANFD_TR_FIFO10, CYHAL_SIGNAL_TYPE_LEVEL), //!< canfd.tr_fifo1[0]
    CYHAL_TRIGGER_CANFD_TR_TMP_RTP_OUT0 = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CANFD_TR_TMP_RTP_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< canfd.tr_tmp_rtp_out[0]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[0]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[1]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[2]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[2]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[3]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[3]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[4]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[4]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[5]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[5]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[6]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[6]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[7]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[7]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[8]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[8]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[9]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[9]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[10]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[10]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[11]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[11]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[12]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[12]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[13]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[13]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[14]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[14]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15, CYHAL_SIGNAL_TYPE_EDGE), //!< cpuss.dmac_tr_out[15]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15, CYHAL_SIGNAL_TYPE_LEVEL), //!< cpuss.dmac_tr_out[15]
    CYHAL_TRIGGER_EXCO_TRIGGER_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_EXCO_TRIGGER, CYHAL_SIGNAL_TYPE_EDGE), //!< exco.trigger
    CYHAL_TRIGGER_EXCO_TRIGGER_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_EXCO_TRIGGER, CYHAL_SIGNAL_TYPE_LEVEL), //!< exco.trigger
    CYHAL_TRIGGER_LPCOMP_COMP_OUT0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_LPCOMP_COMP_OUT0, CYHAL_SIGNAL_TYPE_EDGE), //!< lpcomp.comp_out[0]
    CYHAL_TRIGGER_LPCOMP_COMP_OUT0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_LPCOMP_COMP_OUT0, CYHAL_SIGNAL_TYPE_LEVEL), //!< lpcomp.comp_out[0]
    CYHAL_TRIGGER_LPCOMP_COMP_OUT1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_LPCOMP_COMP_OUT1, CYHAL_SIGNAL_TYPE_EDGE), //!< lpcomp.comp_out[1]
    CYHAL_TRIGGER_LPCOMP_COMP_OUT1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_LPCOMP_COMP_OUT1, CYHAL_SIGNAL_TYPE_LEVEL), //!< lpcomp.comp_out[1]
    CYHAL_TRIGGER_MSC0_TR_RD_REQ_OUT = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_MSC0_TR_RD_REQ_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< msc[0].tr_rd_req_out
    CYHAL_TRIGGER_MSC1_TR_RD_REQ_OUT = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_MSC1_TR_RD_REQ_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< msc[1].tr_rd_req_out
    CYHAL_TRIGGER_MSC0_TR_WR_REQ_OUT = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_MSC0_TR_WR_REQ_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< msc[0].tr_wr_req_out
    CYHAL_TRIGGER_MSC1_TR_WR_REQ_OUT = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_MSC1_TR_WR_REQ_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< msc[1].tr_wr_req_out
    CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0, CYHAL_SIGNAL_TYPE_EDGE), //!< pass[0].dsi_ctb_cmp0
    CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0, CYHAL_SIGNAL_TYPE_LEVEL), //!< pass[0].dsi_ctb_cmp0
    CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1, CYHAL_SIGNAL_TYPE_EDGE), //!< pass[0].dsi_ctb_cmp1
    CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1, CYHAL_SIGNAL_TYPE_LEVEL), //!< pass[0].dsi_ctb_cmp1
    CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE, CYHAL_SIGNAL_TYPE_EDGE), //!< pass[0].dsi_sar_sample_done
    CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE, CYHAL_SIGNAL_TYPE_LEVEL), //!< pass[0].dsi_sar_sample_done
    CYHAL_TRIGGER_PASS0_TR_SAR_OUT_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_TR_SAR_OUT, CYHAL_SIGNAL_TYPE_EDGE), //!< pass[0].tr_sar_out
    CYHAL_TRIGGER_PASS0_TR_SAR_OUT_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_PASS0_TR_SAR_OUT, CYHAL_SIGNAL_TYPE_LEVEL), //!< pass[0].tr_sar_out
    CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_i2c_scl_filtered
    CYHAL_TRIGGER_SCB0_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_rx_req
    CYHAL_TRIGGER_SCB1_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_rx_req
    CYHAL_TRIGGER_SCB2_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_rx_req
    CYHAL_TRIGGER_SCB3_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_rx_req
    CYHAL_TRIGGER_SCB4_TR_RX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_RX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_rx_req
    CYHAL_TRIGGER_SCB0_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB0_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[0].tr_tx_req
    CYHAL_TRIGGER_SCB1_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB1_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[1].tr_tx_req
    CYHAL_TRIGGER_SCB2_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB2_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[2].tr_tx_req
    CYHAL_TRIGGER_SCB3_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB3_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[3].tr_tx_req
    CYHAL_TRIGGER_SCB4_TR_TX_REQ = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_SCB4_TR_TX_REQ, CYHAL_SIGNAL_TYPE_LEVEL), //!< scb[4].tr_tx_req
    CYHAL_TRIGGER_TCPWM_LINE0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[0]
    CYHAL_TRIGGER_TCPWM_LINE0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[0]
    CYHAL_TRIGGER_TCPWM_LINE1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[1]
    CYHAL_TRIGGER_TCPWM_LINE1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[1]
    CYHAL_TRIGGER_TCPWM_LINE2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[2]
    CYHAL_TRIGGER_TCPWM_LINE2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE2, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[2]
    CYHAL_TRIGGER_TCPWM_LINE3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[3]
    CYHAL_TRIGGER_TCPWM_LINE3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE3, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[3]
    CYHAL_TRIGGER_TCPWM_LINE4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[4]
    CYHAL_TRIGGER_TCPWM_LINE4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE4, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[4]
    CYHAL_TRIGGER_TCPWM_LINE5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[5]
    CYHAL_TRIGGER_TCPWM_LINE5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE5, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[5]
    CYHAL_TRIGGER_TCPWM_LINE6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[6]
    CYHAL_TRIGGER_TCPWM_LINE6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE6, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[6]
    CYHAL_TRIGGER_TCPWM_LINE7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.line[7]
    CYHAL_TRIGGER_TCPWM_LINE7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_LINE7, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.line[7]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[0]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[0]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[1]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[1]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[2]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[2]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[3]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[3]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[4]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[4]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[5]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[5]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[6]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[6]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_compare_match[7]
    CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_compare_match[7]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[0]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[0]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[1]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[1]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[2]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[2]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[3]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[3]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[4]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[4]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[5]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[5]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[6]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[6]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_overflow[7]
    CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_overflow[7]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[0]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[0]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[1]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[1]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[2]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[2]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[3]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[3]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[4]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[4]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[5]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[5]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[6]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[6]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7_EDGE = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7, CYHAL_SIGNAL_TYPE_EDGE), //!< tcpwm.tr_underflow[7]
    CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7_LEVEL = _CYHAL_TRIGGER_CREATE_SOURCE(_CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7, CYHAL_SIGNAL_TYPE_LEVEL), //!< tcpwm.tr_underflow[7]
} cyhal_trigger_source_psoc4100smax_t;

/** Typedef from device family specific trigger source to generic trigger source */
typedef cyhal_trigger_source_psoc4100smax_t cyhal_source_t;

/** Deprecated defines for signals that can be either level or edge. */
#define CYHAL_TRIGGER_CPUSS_ZERO (CYHAL_TRIGGER_CPUSS_ZERO_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT8_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT9_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT10_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT11_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT12_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT13_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT14_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15 (CYHAL_TRIGGER_CPUSS_DMAC_TR_OUT15_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_EXCO_TRIGGER (CYHAL_TRIGGER_EXCO_TRIGGER_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_LPCOMP_COMP_OUT0 (CYHAL_TRIGGER_LPCOMP_COMP_OUT0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_LPCOMP_COMP_OUT1 (CYHAL_TRIGGER_LPCOMP_COMP_OUT1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0 (CYHAL_TRIGGER_PASS0_DSI_CTB_CMP0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1 (CYHAL_TRIGGER_PASS0_DSI_CTB_CMP1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE (CYHAL_TRIGGER_PASS0_DSI_SAR_SAMPLE_DONE_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_PASS0_TR_SAR_OUT (CYHAL_TRIGGER_PASS0_TR_SAR_OUT_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE0 (CYHAL_TRIGGER_TCPWM_LINE0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE1 (CYHAL_TRIGGER_TCPWM_LINE1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE2 (CYHAL_TRIGGER_TCPWM_LINE2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE3 (CYHAL_TRIGGER_TCPWM_LINE3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE4 (CYHAL_TRIGGER_TCPWM_LINE4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE5 (CYHAL_TRIGGER_TCPWM_LINE5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE6 (CYHAL_TRIGGER_TCPWM_LINE6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_LINE7 (CYHAL_TRIGGER_TCPWM_LINE7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7 (CYHAL_TRIGGER_TCPWM_TR_COMPARE_MATCH7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7 (CYHAL_TRIGGER_TCPWM_TR_OVERFLOW7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW0_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW1_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW2_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW3_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW4_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW5_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW6_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.
#define CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7 (CYHAL_TRIGGER_TCPWM_TR_UNDERFLOW7_LEVEL) //!< Legacy define. Instead, use the explicit _LEVEL or _EDGE version.

/** @brief Name of each output trigger. */
typedef enum
{
    CYHAL_TRIGGER_CANFD_TR_DBG_DMA_ACK0 = 0, //!< DMA_Requests - canfd.tr_dbg_dma_ack[0]
    CYHAL_TRIGGER_CANFD_TR_EVT_SWT_IN0 = 1, //!< DMA_Requests - canfd.tr_evt_swt_in[0]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN0 = 2, //!< DMA_Requests - cpuss.dmac_tr_in[0]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN1 = 3, //!< DMA_Requests - cpuss.dmac_tr_in[1]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN2 = 4, //!< DMA_Requests - cpuss.dmac_tr_in[2]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN3 = 5, //!< DMA_Requests - cpuss.dmac_tr_in[3]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN4 = 6, //!< DMA_Requests - cpuss.dmac_tr_in[4]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN5 = 7, //!< DMA_Requests - cpuss.dmac_tr_in[5]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN6 = 8, //!< DMA_Requests - cpuss.dmac_tr_in[6]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN7 = 9, //!< DMA_Requests - cpuss.dmac_tr_in[7]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN8 = 10, //!< DMA_Requests - cpuss.dmac_tr_in[8]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN9 = 11, //!< DMA_Requests - cpuss.dmac_tr_in[9]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN10 = 12, //!< DMA_Requests - cpuss.dmac_tr_in[10]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN11 = 13, //!< DMA_Requests - cpuss.dmac_tr_in[11]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN12 = 14, //!< DMA_Requests - cpuss.dmac_tr_in[12]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN13 = 15, //!< DMA_Requests - cpuss.dmac_tr_in[13]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN14 = 16, //!< DMA_Requests - cpuss.dmac_tr_in[14]
    CYHAL_TRIGGER_CPUSS_DMAC_TR_IN15 = 17, //!< DMA_Requests - cpuss.dmac_tr_in[15]
    CYHAL_TRIGGER_MSC0_TR_RD_REQ_IN = 18, //!< CSD Triggers - msc[0].tr_rd_req_in
    CYHAL_TRIGGER_MSC1_TR_RD_REQ_IN = 19, //!< CSD Triggers - msc[1].tr_rd_req_in
    CYHAL_TRIGGER_MSC0_TR_WR_REQ_IN = 20, //!< CSD Triggers - msc[0].tr_wr_req_in
    CYHAL_TRIGGER_MSC1_TR_WR_REQ_IN = 21, //!< CSD Triggers - msc[1].tr_wr_req_in
    CYHAL_TRIGGER_PASS0_TR_SAR_IN = 22, //!< PASS Triggers - pass[0].tr_sar_in
    CYHAL_TRIGGER_TCPWM_TR_IN7 = 23, //!< TCPWM Triggers - tcpwm.tr_in[7]
    CYHAL_TRIGGER_TCPWM_TR_IN8 = 24, //!< TCPWM Triggers - tcpwm.tr_in[8]
    CYHAL_TRIGGER_TCPWM_TR_IN9 = 25, //!< TCPWM Triggers - tcpwm.tr_in[9]
    CYHAL_TRIGGER_TCPWM_TR_IN10 = 26, //!< TCPWM Triggers - tcpwm.tr_in[10]
    CYHAL_TRIGGER_TCPWM_TR_IN11 = 27, //!< TCPWM Triggers - tcpwm.tr_in[11]
    CYHAL_TRIGGER_TCPWM_TR_IN12 = 28, //!< TCPWM Triggers - tcpwm.tr_in[12]
    CYHAL_TRIGGER_TCPWM_TR_IN13 = 29, //!< TCPWM Triggers - tcpwm.tr_in[13]
} cyhal_trigger_dest_psoc4100smax_t;

/** Typedef from device family specific trigger dest to generic trigger dest */
typedef cyhal_trigger_dest_psoc4100smax_t cyhal_dest_t;

/** \cond INTERNAL */
/** Table of number of inputs to each mux. */
extern const uint16_t cyhal_sources_per_mux[4];

/** Table indicating whether mux is 1to1. */
extern const bool cyhal_is_mux_1to1[4];

/** Table pointing to each mux source table. The index of each source in the table is its mux input index. */
extern const _cyhal_trigger_source_psoc4100smax_t* cyhal_mux_to_sources [4];

/** Maps each cyhal_destination_t to a mux index.
 * If bit 8 of the mux index is set, this denotes that the trigger is a
 * one to one trigger.
 */
extern const uint8_t cyhal_dest_to_mux[30];

/* Maps each cyhal_destination_t to a specific output in its mux */
extern const uint8_t cyhal_mux_dest_index[30];
/** \endcond */

#if defined(__cplusplus)
}
#endif /* __cplusplus */
/** \} group_hal_impl_triggers_psoc4100smax */
#endif /* _CYHAL_TRIGGERS_PSOC4100SMAX_H_ */


/* [] END OF FILE */
