/*******************************************************************************
* File Name: mtbcfg_ezpd.c
*
* Description:
* PD stack middleware configuration.
* This file should not be modified. It was automatically generated by
* EZ-PD Configurator 1.20.0.6850
*
********************************************************************************
* \copyright
* Copyright 2022 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "mtbcfg_ezpd.h"

/*******************************************************************************
* PD Port Configuration Structure Initialization
*******************************************************************************/
#if defined(PD_PORT0_ENABLED)
const cy_stc_pdstack_port_cfg_t mtb_usbpd_port0_pdstack_config = 
{
    .signature = 0x50445343, /* PDSC */ 
    .version = 0x0100, /* Configuration table version */ 
    .mfgLenInfo = 0x0D, /* Length of Manufacturer Information */ 
    .mfgVid = 0x04B4, /* Manufacturer Vendor ID */ 
    .mfgPid = 0xF500, /* Manufacturer Product ID */ 
    .mfgName = "Infineon", /* Manufacturer Name */ 
    .scedbEn = 0, /* SCEDB enable */ 
    .skedbEn = 1, /* SKEDB enable */ 
    .extSrcCap = {0}, /* SCEDB Configuration */ 
    .extSnkCap = {0}, /* SKEDB Configuration */ 
    .portRole = 1, /* Port role */ 
    .defPortRole = 1, /* Default port role */ 
    .curLevel = 2, /* Current level */ 
    .cableDiscCount = 0x14, /* Cable Discover count */ 
    .srcPdoFlags = {0x70,0x00}, /* Source PDO flags */ 
    .snkPdoFlags = {0}, /* Sink PDO flags */ 
    .drpToggleEn = 0, /* DRP toggle enable */ 
    .rpSupported = 0, /* Rp supported */ 
    .pdOpEn = 1, /* PD operation enable */ 
    .prefPwrRole = 0, /* Preferred Power role */ 
    .portDis = 0, /* Port disable */ 
    .cableDiscEn = 0, /* Cable Discovery Enable */ 
    .deadBatSupp = 1, /* Dead battery support */ 
    .errorRecoveryEn = 1, /* Error recovery enable */ 
    .accessoryEn = 1, /* Accessory mode enable */ 
    .rpDetachEn = 1, /* Rp detach enable */ 
    .vconnRetain = 0, /* VCONN retain */ 
    .frsConfig = 0, /* FRS configuration */ 
    .srcPdoCount = 0x04, /* Source PDO count */ 
    .defSrcPdoMask = 0x0D, /* Default Source PDO mask */ 
    .snkPdoCount = 0x00, /* Sink PDO count */ 
    .defSnkPdoMask = 0x00, /* Default Sink PDO mask */ 
    .srcPdo = {0x0701912C,0x0002D12C,0x0004B12C,0x000641F4}, /* Source PDO */ 
    .snkPdo = {0}, /* Sink PDO */ 
    .snkPdoMinMaxCur = {0}, /* Sink PDO min/max current */ 
    .eprSrcPdoCount = 0x02, /* EPR Source PDO count */ 
    .eprSrcPdoMask = 0x03, /* Default EPR Source PDO mask */ 
    .eprSnkPdoCount = 0x00, /* EPR Sink PDO count */ 
    .eprSnkPdoMask = 0x00, /* Default EPR Sink PDO mask */ 
    .pdRevision = 0x31100000, /* Get_Revision message response */ 
    .srcInfo = 0x803C3C3C, /* Get_Source_Info message response */ 
    .eprSrcPdo = {0x0008C1F4,0xD12C9654}, /* EPR Source PDO */ 
    .eprSnkPdo = {0}, /* EPR Sink PDO */ 
};
#endif


/* [] END OF FILE */
